# Generated by Django 6.1.1 on 2026-09-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='featured/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
